const GET_PRODUCTS = 'GET_PRODUCTS';
const ADD_PRODUCT = 'ADD_PRODUCT';
const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
const TOGGLE_OPEN = 'TOGGLE_OPEN';

export { GET_PRODUCTS, ADD_PRODUCT, REMOVE_PRODUCT, TOGGLE_OPEN };
